services:
  app:
    build: .
    container_name: gymware_app
    ports:
      - "8000:80" # localhost:8000 â†’ container port 80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=gymware
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
    command: php artisan serve --host=0.0.0.0 --port=80

  db:
    image: mysql:8.0
    container_name: gymware_db
    restart: always
    environment:
      MYSQL_DATABASE: gymware
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:
